import { useState, FormEvent, useEffect } from "react";
import { ThreeDots } from "react-loader-spinner";

import { convertImage } from "../utils/imageUtils";
import { extractText } from "../api/PSAPI";
import { ExtractResponse } from "../types/text";


const Writer = (props: {text: string | undefined, headings: string[] | undefined}) => {
    const separatedHeadings: string[] = [];
    const textSections: string[] | undefined = props.text?.split("\n\n");

    // split the headings array properly
    const tempHeadings: string[][] = props.headings ? props.headings.map(element => element.split("\n\n")) : [];

    tempHeadings.map(element => {
        if (typeof(element) === 'object') {
            for (let i=0 ; i<element.length ; i++) {
                separatedHeadings.push(element[i]);
            }
        } else {
            separatedHeadings.push(element);
        }
    })

    // fully separated/splitted headings
    const finalHeadings: string[] = separatedHeadings.map(element => element.replace("\n", ""));

    // split sections to array of words (BM~bionic method)
    const BMArray = []
    if (textSections) {
        for (let i = 0 ; i < textSections.length ; i++) {
            BMArray.push(textSections[i].split(" "))
        }
    }
    
    return (
        <div>
            <div className="flex w-full items-center justify-center">
                <h3 className="text-sm">--Generated by @PixelScript--</h3>
            </div>
            {
                // apply bionic reading method algorithm
                BMArray.map((section, index) => {
                    const fHalfSection: string[] = [];
                    const lHalfSection: string[] = [];
                    const wordCount: number = section.length;


                    // separate all words in eact section
                    for (let i = 0 ; i < wordCount ; i++) {
                        const word: string = section[i].replace("\n", " ");
                        const charsLength: number = word.length;
                        const bold: number = Math.ceil(charsLength / 2);
                        const fHalf: string = word.slice(0, bold)
                        const lHalf: string = word.slice(bold, charsLength)

                        fHalfSection.push(fHalf);
                        lHalfSection.push(lHalf + " ");
                    }

                    // headings
                    if (finalHeadings.includes(textSections? textSections[index].replace("\n", "") : "")) {
                        return (
                            <div key={`d${index}`}>
                                <p className="flex flex-wrap text-black">
                                    {
                                        // map each section to return word with bionic method applied
                                        fHalfSection.map((word, index_n) => (
                                            <span key={`s${index_n}`}>
                                                <span className="text-[20px] font-light leading-[30px]">
                                                    <b className="font-semibold">{word}</b>{lHalfSection[index_n]}
                                                </span>
                                                &nbsp;
                                            </span>
                                        ))
                                    }
                                </p>
                                &nbsp;
                            </div>
                        )
                    }

                    return (
                        // paragraphs / sentences
                        <div key={`d${index}`}>
                            <p className="flex flex-wrap text-black">
                                {
                                    // map each section to return word with bionic method applied
                                    fHalfSection.map((word, index_n) => (
                                        <span key={`s${index_n}`}>
                                            <span className="text-[16px] font-light leading-[30px]">
                                                <b className="font-semibold">{word}</b>{lHalfSection[index_n]}
                                            </span>
                                            &nbsp;
                                        </span>
                                    ))
                                }
                            </p>
                            &nbsp;
                        </div>
                    )
                })
            }
        </div>
    )
}


const DocumentViewer = (props: {response: ExtractResponse | null}) => {
    
    return (
            <div id="document" className="bg-[#eefeff] sm:w-[55vw] w-full h-[55vh] rounded-xl overflow-y-auto p-5 scrolling">
                <Writer text={props.response?.text} headings={props.response?.headings} />
            </div>
    )
}

export const ImageSection = () => {
    const [image, setImage] = useState<string>("");
    const [uploadedImage, setUploadedImage] = useState<File | null>(null);
    const [response, setResponse] = useState<ExtractResponse | null>(null);
    const [loading, setLoading] = useState<boolean>(false);

    const handleChange = (e: FormEvent<HTMLInputElement>) => {
        const inputValue: FileList | null = e.currentTarget.files;

        convertImage(inputValue, setImage);
        setUploadedImage(inputValue ? inputValue[0] : inputValue);
    }

    const handleClick = () => {
        setLoading(true);

        const imageFile: File | null = uploadedImage;
        extractText({imageFile, setResponse});
    }

    const handleDownloadOnClick = () => {
        const filename: string = response ? "PS" + response.date + "~" + response.id + ".doc" : '';
        
        const element: string = (document.getElementById("document") as HTMLInputElement).innerText;
        const formatted: string = element.replace(/[\u00A0\u180E\u2000-\u200B\u202F\u205F\u3000\uFEFF]/g, "").replace(/ \n/g, " ");

        
        const downloadLink: HTMLAnchorElement = document.createElement('a');

        downloadLink.setAttribute("download", filename);
        downloadLink.setAttribute("href", "data:" + "text/docx;" + "charset=utf-8," + encodeURIComponent(formatted))

        downloadLink.click();
    }

    useEffect(() => {
        setLoading(false);
    }, [response])

    return (
        <section className="bg-[#374151] w-full h-screen sm:pt-20 pt-16">
            <div className="w-full h-full flex flex-col items-center justify-center gap-5 p-10">
                <div className={response ? 'hidden' : 'bg-[#293241] flex flex-col items-center justify-center sm:w-[400px] w-full min-h-[400px] rounded-3xl sm:p-10 gap-5 p-5'}>
                    <span className="text-[30px] text-[#e0fbfc]">Add your image</span>
                    <p className={image === "" ? 'text-[#ffffff] font-light text-[16px] tracking-widest leading-[30px] py-5' : 'hidden'}>
                        Add an image using your camera or add from your files.
                    </p>

                    <p className={image === "" ? 'hidden' : 'text-[#ffffff] font-light text-[16px] tracking-widest leading-[30px]'}>
                        Preview:
                    </p>

                    {
                        image === "" ?
                        "" :
                        <img src={image} alt="image" className="w-60" />
                    }
                    
                    <form
                        onSubmit={(e: FormEvent<HTMLFormElement>) => {
                            e.preventDefault();
                        }}
                    >
                        <div className={image === "" ? 'flex gap-10' : 'hidden'}>
                            <button
                                onClick={() => {
                                    document.getElementById("cameraFile")?.click();
                                }}
                                className="bg-[#00ffef] text-[#374151] rounded-lg w-28 h-10 hover:bg-[#77fff7] button-hover"
                            >
                                Camera
                            </button>
                            <input 
                                id="cameraFile"
                                name="cameraFile"
                                type="file" 
                                accept="image/*" 
                                capture="user" 
                                style={{
                                    display: "none"
                                }}
                                onChange={handleChange}
                            />

                            <button
                                onClick={() => {
                                    document.getElementById("uploadFile")?.click();
                                }}
                                className="bg-[#00ffef] text-[#374151] rounded-lg w-28 h-10 hover:bg-[#77fff7] button-hover"
                            >
                                Files
                            </button>
                            <input 
                                id="uploadFile"
                                name="uploadFile"
                                type="file" 
                                accept="image/*"
                                style={{
                                    display: "none"
                                }}
                                onChange={handleChange}
                            />
                        </div>

                        <div className={image === "" ? 'hidden' : 'flex '}>
                            <div className={!loading ? 'flex gap-10' : 'hidden'}>
                                <button
                                    className="bg-[#00ffef] text-[#374151] rounded-lg w-28 h-10 hover:bg-[#77fff7] button-hover"
                                    onClick={() => {
                                        setImage("");
                                    }}
                                >
                                    Back
                                </button>

                                <button
                                    className="bg-[#00ffef] text-[#374151] rounded-lg w-28 h-10 hover:bg-[#77fff7] button-hover"
                                    onClick={handleClick}
                                >
                                    Continue
                                </button>
                            </div>
                        
                            {loading ? <ThreeDots height={50} width={50} color="#00ffef" /> : null}
                        </div>
                    </form>
                </div>

                <div className={response ? 'bg-[#293241] flex flex-col w-full overflow-auto h-full rounded-2xl p-5 gap-3 scrolling' : 'hidden'}>
                    <h2 className="text-[30px] text-[#e0fbfc]">Extracted Text [Bionic Reading Method]</h2>
                    <div className="flex sm:flex-row flex-col w-full sm:gap-20 gap-10">
                        <DocumentViewer response={response} />
                        <div className="sm:w-[30vw] w-full justify-center">
                            <h2 className="text-[30px] text-[#e0fbfc]">Info</h2>
                            <p className="text-white text-[16px] font-light tracking-widest leading-[30px] pt-5 sm:mr-10">
                                Below you can download the extracted text as a word document which you can easily edit. 
                                The text in the document does not have the bionic reading method appied.
                            </p>
                        </div>
                    </div>

                    <div className="flex flex-row w-full gap-5 pt-5 justify-center">
                    <button
                        onClick={() => {
                            setResponse(null);
                            setImage("");
                        }}
                            className="bg-[#00ffef] text-[#374151] rounded-lg w-24 h-10 hover:bg-[#77fff7] button-hover"
                        >
                           Back
                        </button>
                        <button
                        onClick={handleDownloadOnClick}
                            className="bg-[#00ffef] text-[#374151] rounded-lg w-24 h-10 hover:bg-[#77fff7] button-hover"
                        >
                            Download
                        </button>
                    </div>
                </div>
            </div>
        </section>
    )
}
